version: "3"
services:
 mongodb:
  image: bitnami/mongodb:4.4
  container_name: mongodb
  restart: always
  environment:
   MONGODB_USERNAME: thf4
   MONGODB_PASSWORD: 3268
   MONGODB_DATABASE: Frexco
  networks:
   - backend
  ports:
   - "27017:27017"

 node:
  build:
   dockerfile: ./Docker/frexco.dockerfile
   context: .
  container_name: frexco
  volumes:
   - ./BackEnd:/home/app
  restart: always
  environment:
   NODE_ENV: development
   MONGODB: mongodb:27017
   MONGODB_USER: thf4
   MONGODB_PASS: 3268
  ports:
   - "3000:3000"
  depends_on:
   - mongodb
  networks:
   - backend

networks:
 backend:
  driver: bridge
