version: "3"
services:
 mongodb:
  image: "mongo"
  container_name: mongodb
  restart: always
  environment:
   MONGO_INITDB_ROOT_USERNAME: root
   MONGO_INITDB_ROOT_PASSWORD: example
  networks:
   - bridge
  ports:
   - "27017:27017"

 node:
  build:
   dockerfile: ./Docker/frexco.dockerfile
   context: .
  container_name: frexco
  volumes:
   - ./BackEnd:/home/app
  restart: always
  environment:
   - NODE_ENV=development
  ports:
   - "3000:3000"
  depends_on:
   - mongodb
  networks:
   - bridge

networks:
 bridge:
  driver: bridge
