version: "3"
services:
 mongodb:
  image: "mongo"
  restart: always
  ports:
   - "27017:27017"

 node:
  build:
   dockerfile: ./Docker/frexco.dockerfile
   context: .
  image: thalesf/frexco
  container_name: frexco1
  restart: always
  ports:
   - "3000"
  depends_on:
   - "mongodb"
