version: "3"
services:
 mongodb:
  image: "mongo"
  networks:
   - production

 node:
  build:
   dockerfile: ./docker/frexco.dockerfile
   context: .
  image: thalesf/frexco
  container_name: alurabooks1
  ports:
   - "3000"
  networks:
   - production
  depends_on:
   - "mongodb"

networks:
 production:
  driver: bridge
