version: "3"
services:
 mongodb:
  image: "mongo"
  restart: always
  networks:
   - bridge

 node:
  build:
   dockerfile: ./Docker/frexco.dockerfile
   context: .
  image: thalesf/frexco
  container_name: frexco1
  volumes:
   - ./:/home/node/app
  restart: always
  environment:
   - NODE_ENV=development
  ports:
   - "3000"
  depends_on:
   - "mongodb"
  networks:
   - bridge

networks:
 bridge:
  driver: bridge
