version: 3
services:
 node:
  build:
  dockerfile: ./docker/frexco.dockerfile
  context: .
 image: thalesf/frexco
 container_name: frexco
 ports:
  - "3000"
 networks:
  - production

  mongodb:
    image: mongo
    networks:
     - production
networks:
 production:
  driver: bridge
