version: "3"
services:
 mongodb:
  image: mongo
  networks:
   - production

 node:
  build:
  dockerfile: ./docker/frexco.dockerfile
  context: .
 image: thalesf/frexco
 container_name: frexco
 ports:
  - "3000"
 networks:
  - production

networks:
 production:
  driver: bridge
